# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- publish
- gitlab-test
- lint
- test

###############################################################################
#################### actions
###############################################################################

variables:
  ANSIBLE_FORCE_COLOR: 'true'
  PY_COLORS: '1'
  #
  DOCKER_IMAGE_DOCKER_DIND_MOLECULE: robincbz/docker-dind-molecule:latest
  DOCKER_IMAGE_DOCKER_DIND_ANSIBLE: robincbz/docker-dind-ansible:latest
  DOCKER_IMAGE_ANSIBLE_LINT: robincbz/alpine-ansiblelint:latest
  DOCKER_IMAGE_JINJA_LINT: robincbz/alpine-jinjalint:latest
  DOCKER_IMAGE_YAML_LINT: robincbz/alpine-yamllint:latest
  DOCKER_IMAGE_DEBIAN_11_ANSIBLE: robincbz/debian-11-ansible:latest
  DOCKER_IMAGE_DEBIAN_12_ANSIBLE: robincbz/debian-12-ansible:latest

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

yaml_lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_YAML_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - yamllint --list-files ./
    - yamllint -c ./.yamllint ./
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"

jinja_lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_JINJA_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - "[ -n \"$(find ./templates -name '*.j2')\" ] && j2lint ./templates/*.j2 --ignore S3 S7"
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"

ansible_lint:
  stage: lint
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_ANSIBLE_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - ansible-lint --config=./.ansible-lint --exclude molecule --exclude tests ./*
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"

.molecule_test: &molecule_test
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_DIND_MOLECULE
  stage: test
  before_script:
    - "docker login -u \"$NEXUS_REPOS_USERNAME\" -p \"$NEXUS_REPOS_PASSWORD\" \"http://$NEXUS_REPOS_DOCKER_REGISTRY\""
    - "python3 -m compileall /usr/lib/python3 -qq"
    - "cp ./.ansible.cfg /root/.ansible.cfg"
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
    - "[ -f \"./molecule/$SCENARIO/requirements.yml\" ] && ansible-galaxy install -r ./molecule/$SCENARIO/requirements.yml --roles-path=./molecule/$SCENARIO/roles"
  script:
    - "molecule test --scenario-name $SCENARIO"
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"

.publish_release: &publish_release
  image: $NEXUS_REPOS_DOCKER_REGISTRY/$DOCKER_IMAGE_DOCKER_DIND_ANSIBLE
  stage: publish
  before_script:
    - TAGS=$(git ls-remote --tags origin | awk '{print $2}' | grep -oE 'refs/tags/[0-9.]+' | cut -d '/' -f 3 | sort -V)
    - LATEST_TAG=$(echo "$TAGS" | tail -n 1)
    - MAJOR_VERSION=$(echo "$LATEST_TAG" | grep -oE '^[0-9]+')
    - MAJOR_VERSION=$((MAJOR_VERSION + 1))
    - TIMESTAMP=$(date +'%Y%m%d-%H.%M.%S')
    - RC_BRANCH_NAME="RC-$MAJOR_VERSION.0-$TIMESTAMP"
  script:
    - "git config user.email \"$GITLAB_USER_EMAIL\""
    - "git config user.name \"$GITLAB_USER_EMAIL\""
    - "git remote add rc_origin \"$CI_REPOSITORY_URL\""
    - "git checkout \"$CI_DEFAULT_BRANCH\""
    - "git checkout -b \"$RC_BRANCH_NAME\""
    - "git add ."
    - "git push rc_origin \"$RC_BRANCH_NAME\""
  allow_failure: false

###############################################################################
#################### CICD
###############################################################################

molecule_test_debian_11:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-debian-11"
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"

molecule_test_debian_12:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-debian-12"
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
  needs:
    - "molecule_test_debian_11"

molecule_test_ubuntu_22:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-ubuntu-22"
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
  needs:
    - "molecule_test_debian_12"

publish_release_candidate:
  <<: *publish_release
  variables:
    CI_JOB_TOKEN: $CICD_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"
