---
dependency:
  name: "galaxy"
  options:
    ignore-certs: true

driver:
  name: "docker"

platforms:
  - name: "molecule-local-instance-1-prepare-host"
    image: "robincbz/debian-12-ansible:latest"
    hostname: "molecule-local-instance-1-prepare-host"
    #published_ports:
    #  - "0.0.0.0:8181:8181/tcp"
    privileged: true
    pre_build_image: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    storage_driver: "overlay2"
    networks:
      - name: "molecule-default-prepare-host"

provisioner:
  name: "ansible"
  inventory:
    links:
      hosts: "../../tests/inventory/hosts.yml"
      group_vars: "../../tests/inventory/group_vars/"
      host_vars: "../../tests/inventory/host_vars/"
  options:
    extra-vars: "@./tests/tower/tower.yml"
  log: ${MOLECULE_ANSIBLE_LOG:-true}
  env:
    ANSIBLE_CONFIG: "../../.ansible.cfg"
    ANSIBLE_FORCE_COLOR: "true"
    # disable nologs
    MOLECULE_NOLOG: 0
    # disable destroy
    MOLECULE_DESTROY: "never"
    # debug mode (same as --debug) -- very verbose
    MOLECULE_DEBUG: 1
    # change ansible own verbosity
    ANSIBLE_VERBOSITY: 1

verifier:
  name: "ansible"

scenario:
  name: "default"
  test_sequence:
    - "destroy"
    - "syntax"
    - "dependency"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
